spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springboot
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    thymeleaf:
        cache: false
        mode: LEGACYHTML5